/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "add.h"

bool_t
xdr_integer (XDR *xdrs, integer *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_filename (XDR *xdrs, filename *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXNAMELEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_point (XDR *xdrs, point *objp)
{
	register int32_t *buf;

	 if (!xdr_integer (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_integer (xdrs, &objp->y))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_shape (XDR *xdrs, shape *objp)
{
	register int32_t *buf;

	 if (!xdr_integer (xdrs, &objp->type))
		 return FALSE;
	switch (objp->type) {
	case 1:
		 if (!xdr_integer (xdrs, &objp->shape_u.square_side))
			 return FALSE;
		break;
	case 2:
		 if (!xdr_integer (xdrs, &objp->shape_u.circle_radius))
			 return FALSE;
		break;
	default:
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_point2d (XDR *xdrs, point2d *objp)
{
	register int32_t *buf;

	 if (!xdr_point (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_point3d (XDR *xdrs, point3d *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->point3d_val, (u_int *) &objp->point3d_len, 3,
		sizeof (point2d), (xdrproc_t) xdr_point2d))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_filename_list (XDR *xdrs, filename_list *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, ~0))
		 return FALSE;
	return TRUE;
}
